create table if not exists public.odds_line_current (
  line_key text primary key,
  mode text not null check (mode in ('draft', 'weekly')),
  season integer not null,
  scope text not null check (scope in ('season', 'game')),
  event_key text not null,
  event_id text,
  entity_type text not null check (entity_type in ('player', 'game')),
  entity_id text not null,
  entity_name text not null,
  position text,
  team text,
  opponent text,
  market text not null,
  book_key text not null,
  book_name text not null,
  line numeric not null,
  opening_line numeric not null,
  over_odds integer,
  under_odds integer,
  source text not null,
  source_updated_at timestamptz,
  first_seen_at timestamptz not null,
  last_seen_at timestamptz not null,
  last_moved_at timestamptz,
  active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists odds_line_current_lookup
  on public.odds_line_current (mode, entity_type, entity_id, market, book_key);
create index if not exists odds_line_current_active
  on public.odds_line_current (mode, active, last_seen_at desc);

create table if not exists public.odds_line_events (
  id bigint generated by default as identity primary key,
  event_fingerprint text not null unique,
  captured_at timestamptz not null,
  mode text not null check (mode in ('draft', 'weekly')),
  season integer not null,
  line_key text not null,
  entity_type text not null check (entity_type in ('player', 'game')),
  entity_id text not null,
  entity_name text not null,
  market text not null,
  book_key text not null,
  book_name text not null,
  change_kind text not null check (change_kind in ('posted', 'moved', 'repriced', 'removed')),
  previous_line numeric,
  line numeric,
  previous_over_odds integer,
  over_odds integer,
  previous_under_odds integer,
  under_odds integer,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists odds_line_events_player_history
  on public.odds_line_events (mode, entity_type, entity_id, captured_at desc);
create index if not exists odds_line_events_recent
  on public.odds_line_events (mode, captured_at desc);

create table if not exists public.odds_capture_runs (
  id bigint generated by default as identity primary key,
  captured_at timestamptz not null,
  mode text not null check (mode in ('draft', 'weekly')),
  status text not null,
  fetched_lines integer not null default 0,
  new_lines integer not null default 0,
  moved_lines integer not null default 0,
  repriced_lines integer not null default 0,
  removed_lines integer not null default 0,
  duration_ms integer not null default 0,
  source_status jsonb not null default '[]'::jsonb,
  error text
);

create index if not exists odds_capture_runs_recent
  on public.odds_capture_runs (mode, captured_at desc);

alter table public.odds_line_current enable row level security;
alter table public.odds_line_events enable row level security;
alter table public.odds_capture_runs enable row level security;

-- No public policies are intentional. The application accesses these tables only
-- from server routes with the Supabase service role key.
